server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: graduate-escape-game
  
  # 정적 리소스 설정
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        cachecontrol:
          max-age: 3600
  
  # CORS 설정
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

# 로깅 설정
logging:
  level:
    com.graduateescape: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# 게임 설정
game:
  version: "1.0.0"
  max-players: 100
  session-timeout: 3600 # 1시간
